apiVersion: v1
kind: ConfigMap
metadata:
  name: ruby-rails
data:
  PORT: "3800"
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_SERVE_STATIC_FILES: "true"
  SECRET_KEY_BASE: "top-secret"
