apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  labels:
    app.kubernetes.io/name: db-migrate
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db-migrate
    spec:
      containers:
      - command:
        - rails
        - db:migrate
        envFrom:
        - configMapRef:
            name: ruby-rails
            image: kuldeepvyadav/ruby:prod
        imagePullPolicy: IfNotPresent
        name: main
      restartPolicy: Never
